version: '3'
services:
  db:
    image: mysql:8
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      dev:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9082:80'
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    networks:
      - dev

  www:
    build: php
    ports:
      - '8007:80'
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
