controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

weather:
    path: /api/weather
    controller: App\Controller\WeatherController::getWeather
    methods: GET